package in.lokeshkaushik.to_do_app.service;

import in.lokeshkaushik.to_do_app.config.SecurityConfig;
import in.lokeshkaushik.to_do_app.dto.UserDto.UserDto;
import in.lokeshkaushik.to_do_app.dto.UserDto.UserLoginDto;
import in.lokeshkaushik.to_do_app.dto.UserDto.UserLoginResponseDto;
import in.lokeshkaushik.to_do_app.dto.UserDto.UserRegistrationDto;
import in.lokeshkaushik.to_do_app.exception.InvalidCredentialsException;
import in.lokeshkaushik.to_do_app.exception.UserAlreadyExistsException;
import in.lokeshkaushik.to_do_app.exception.UserNotFoundException;
import in.lokeshkaushik.to_do_app.model.User;
import in.lokeshkaushik.to_do_app.model.UserPrincipal;
import in.lokeshkaushik.to_do_app.repository.UserRepository;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.*;
import org.springframework.security.authentication.*;
import org.springframework.security.core.Authentication;
import org.springframework.security.crypto.password.PasswordEncoder;

import java.lang.reflect.Field;
import java.util.Optional;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

public class UserServiceTest {

    @Mock
    private UserRepository userRepository;

    @Mock
    private SecurityConfig securityConfig;

    @Mock
    private AuthenticationManager authenticationManager;

    @Mock
    private JwtService jwtService;

    @Mock
    private PasswordEncoder passwordEncoder;

    @InjectMocks
    private UserService userService;

    private AutoCloseable closeable;

    @BeforeEach
    void setup() {
        closeable = MockitoAnnotations.openMocks(this);
        when(securityConfig.passwordEncoder()).thenReturn(passwordEncoder);
    }

    @AfterEach
    void tearDown() throws Exception {
        closeable.close(); // release mock resources
    }

    // ------------------- registerUser() -------------------

    @Test
    void registerUser_success() {
        UserRegistrationDto dto = new UserRegistrationDto("tester", "test@example.com", "pass123");

        when(userRepository.existsByEmailId(dto.emailId())).thenReturn(false);
        when(userRepository.existsByUsername(dto.username())).thenReturn(false);
        when(passwordEncoder.encode(dto.password())).thenReturn("encoded-pass");

        User savedUser = User.builder()
                .username(dto.username())
                .emailId(dto.emailId())
                .password("encoded-pass")
                .build();

        // UUID generation test
        assertNotNull(savedUser.getUuid(), "UUID should be auto-generated by entity constructor");

        when(userRepository.save(any(User.class))).thenAnswer(invocation -> {
            User u = invocation.getArgument(0);
            // simulate DB assigning an uuid
            Field idField = getFieldFromHierarchy(u.getClass(), "id");
            idField.setAccessible(true);
            idField.set(u, 1L);
            return u;
        });

        UserDto result = userService.registerUser(dto);

        assertNotNull(result);
        assertEquals(savedUser.getUsername(), result.username());
        assertEquals(savedUser.getEmailId(), result.emailId());
        verify(userRepository).save(any(User.class));
    }

    @Test
    void registerUser_shouldThrow_WhenEmailExists() {
        UserRegistrationDto dto = new UserRegistrationDto("user1", "existing@example.com", "pass");
        when(userRepository.existsByEmailId(dto.emailId())).thenReturn(true);

        assertThrows(UserAlreadyExistsException.class, () -> userService.registerUser(dto));
    }

    @Test
    void registerUser_shouldThrow_WhenUsernameExists() {
        UserRegistrationDto dto = new UserRegistrationDto("user1", "test@example.com", "pass");
        when(userRepository.existsByUsername(dto.username())).thenReturn(true);

        assertThrows(UserAlreadyExistsException.class, () -> userService.registerUser(dto));
    }

    // helper function for navigating field in super classes
    private static Field getFieldFromHierarchy(Class<?> clazz, String fieldName) throws NoSuchFieldException {
        while (clazz != null) {
            try {
                return clazz.getDeclaredField(fieldName);
            } catch (NoSuchFieldException e) {
                clazz = clazz.getSuperclass();
            }
        }
        throw new NoSuchFieldException(fieldName);
    }


    // ------------------- getUser() -------------------

    @Test
    void getUser_success() {
        UUID uuid = UUID.randomUUID();
        User user = User.builder()
                .username("abc")
                .emailId("abc@xyz.com")
                .build();

        when(userRepository.findByUuid(uuid)).thenReturn(Optional.of(user));

        UserDto result = userService.getUser(uuid);

        assertEquals(user.getUsername(), result.username());
    }

    @Test
    void getUser_shouldThrow_WhenNotFound() {
        UUID uuid = UUID.randomUUID();
        when(userRepository.findByUuid(uuid)).thenReturn(Optional.empty());

        assertThrows(UserNotFoundException.class, () -> userService.getUser(uuid));
    }

    // ------------------- loginUser() -------------------

    @Test
    void loginUser_success() {
        User user = User.builder()
                .username("tester")
                .emailId("t@e.com")
                .password("encoded-pass")
                .build();

        UserPrincipal userPrincipal = new UserPrincipal(user);
        Authentication authentication = mock(Authentication.class);
        when(authentication.getPrincipal()).thenReturn(userPrincipal);
        when(authenticationManager.authenticate(any())).thenReturn(authentication);
        when(jwtService.generateToken(user.getUuid().toString())).thenReturn("jwt-token");

        UserLoginDto loginDto = new UserLoginDto("tester", "pass");

        UserLoginResponseDto response = userService.loginUser(loginDto);

        assertEquals(user.getUsername(), response.username());
        assertEquals("jwt-token", response.jwtToken());
    }

    @Test
    void loginUser_shouldThrow_InvalidCredentials() {
        UserLoginDto loginDto = new UserLoginDto("tester", "wrong");

        when(authenticationManager.authenticate(any()))
                .thenThrow(new BadCredentialsException("Bad credentials"));

        assertThrows(InvalidCredentialsException.class, () -> userService.loginUser(loginDto));
    }

// ------------------- isUsernameAvailable(), isEmailAvailable() -------------------

    @Test
    void isUsernameAvailable_true() {
        when(userRepository.existsByUsername("uniqueUser")).thenReturn(false);
        assertTrue(userService.isUsernameAvailable("uniqueUser"));
    }

    @Test
    void isUsernameAvailable_false() {
        when(userRepository.existsByUsername("takenUser")).thenReturn(true);
        assertFalse(userService.isUsernameAvailable("takenUser"));
    }

    @Test
    void isEmailAvailable_true() {
        when(userRepository.existsByEmailId("new@example.com")).thenReturn(false);
        assertTrue(userService.isEmailAvailable("new@example.com"));
    }

    @Test
    void isEmailAvailable_false() {
        when(userRepository.existsByEmailId("old@example.com")).thenReturn(true);
        assertFalse(userService.isEmailAvailable("old@example.com"));
    }
}
